### ISSUE TITLE
 [26188:27604:0504/181357.623:ERROR:device_event_log_impl.cc(162)] [18:13:57.623] Bluetooth: bluetooth_adapter_winrt.cc:1055 Getting Default Adapter failed.

### ISSUE THREAD

**Issue by jb-0001** [Harshp20/Instagram_Bot#1]
When using the executable file (it doesnt matter if you run it as an operator or not) and trying to log in the following error occurs: 

` Enter your username: [26188:27604:0504/181357.623:ERROR:device_event_log_impl.cc(162)] [18:13:57.623] Bluetooth: bluetooth_adapter_winrt.cc:1055 Getting Default Adapter failed.`

Steps to replicate:
1. Open the executable.
2. Choose option 1 (Log In)
3. Answer no when asked if 2fa is enabled.

You can still type in your username and password, but i get the following error if i try to do so:

```
Check your browser...
Traceback (most recent call last):
  File "InstaBot_Beta.py", line 385, in <module>
  File "InstaBot_Beta.py", line 50, in login
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Please check your Application console window
Message: unexpected alert open: {Alert text : Please check your Application console window}
  (Session info: chrome=81.0.4044.129)

[30192] Failed to execute script InstaBot_Beta
```

Using Windows 10 Home
Version 10.0.17763 Build 17763

**Comment by Harshp20** [comment]
Hey there! You just simply need to hit "Ok" when the message is displayed in the browser which says "Please check your Application console window". Then you can select the login feature and you are good to go!
